CREATE DATABASE IF NOT EXISTS scadaems CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE scadaems;

CREATE TABLE IF NOT EXISTS overview_summary (
  id INT AUTO_INCREMENT PRIMARY KEY,
  `key` VARCHAR(64) NOT NULL UNIQUE,
  value VARCHAR(64) NOT NULL,
  unit VARCHAR(32) NOT NULL DEFAULT '',
  display_order INT NOT NULL DEFAULT 0
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS metrics (
  id INT AUTO_INCREMENT PRIMARY KEY,
  page VARCHAR(32) NOT NULL,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(64) NOT NULL,
  unit VARCHAR(32) NOT NULL DEFAULT '',
  status VARCHAR(32) NOT NULL DEFAULT 'normal',
  display_order INT NOT NULL DEFAULT 0,
  INDEX idx_metrics_page (page, display_order)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS alarms (
  id INT AUTO_INCREMENT PRIMARY KEY,
  page VARCHAR(32) NOT NULL,
  time VARCHAR(16) NOT NULL,
  object VARCHAR(64) NOT NULL,
  message VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL,
  display_order INT NOT NULL DEFAULT 0,
  INDEX idx_alarms_page (page, display_order)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS page_summary (
  id INT AUTO_INCREMENT PRIMARY KEY,
  page VARCHAR(32) NOT NULL,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(128) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'normal',
  display_order INT NOT NULL DEFAULT 0,
  INDEX idx_page_summary_page (page, display_order)
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS simu_bars (
  id INT AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(64) NOT NULL,
  unit VARCHAR(32) NOT NULL DEFAULT '',
  display_order INT NOT NULL DEFAULT 0
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS simu_topology (
  id VARCHAR(64) PRIMARY KEY,
  status VARCHAR(32) NOT NULL DEFAULT 'normal',
  value VARCHAR(64) NOT NULL,
  display_order INT NOT NULL DEFAULT 0
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS simu_daily_curves (
  hour DECIMAL(5,2) PRIMARY KEY,
  wind_speed DECIMAL(10,3) NOT NULL,
  temperature DECIMAL(10,3) NOT NULL,
  solar_irradiance DECIMAL(10,3) NOT NULL,
  load_value DECIMAL(10,3) NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS simu_state (
  id INT PRIMARY KEY,
  sim_time VARCHAR(16) NOT NULL,
  speed DECIMAL(10,3) NOT NULL,
  status VARCHAR(32) NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scada_columns (
  id INT AUTO_INCREMENT PRIMARY KEY,
  label VARCHAR(64) NOT NULL,
  value VARCHAR(64) NOT NULL,
  unit VARCHAR(32) NOT NULL DEFAULT '',
  display_order INT NOT NULL DEFAULT 0
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS scada_stations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'normal',
  detail VARCHAR(128) NOT NULL,
  display_order INT NOT NULL DEFAULT 0
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agc_units (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(64) NOT NULL,
  percent DECIMAL(10,3) NOT NULL,
  power DECIMAL(10,3) NOT NULL,
  unit VARCHAR(32) NOT NULL DEFAULT 'MW',
  display_order INT NOT NULL DEFAULT 0
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS agc_reserve (
  id INT PRIMARY KEY,
  score DECIMAL(10,3) NOT NULL,
  up DECIMAL(10,3) NOT NULL,
  down DECIMAL(10,3) NOT NULL,
  response DECIMAL(10,3) NOT NULL,
  cycle DECIMAL(10,3) NOT NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
